import { Client, Technician, Ticket, BackupHistory, BackupConfig } from './types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'CLI-101',
    name: 'Roberto Alencar',
    company: 'Logística Alfa S.A.',
    email: 'roberto@alfa.com.br',
    phone: '(11) 98765-4321',
    active: true,
  },
  {
    id: 'CLI-102',
    name: 'Carla Dias',
    company: 'Clínica Sorriso do Vale',
    email: 'carla@sorrisovale.com.br',
    phone: '(11) 97654-3210',
    active: true,
  },
  {
    id: 'CLI-103',
    name: 'Marcos Ponci ',
    company: 'Supermercados Sul',
    email: 'marcos@supersul.com.br',
    phone: '(21) 96543-2109',
    active: true,
  },
  {
    id: 'CLI-104',
    name: 'Juliana Mendes',
    company: 'Finanças Premium S.A.',
    email: 'juliana@financaspremium.com',
    phone: '(11) 95432-1098',
    active: true,
  },
  {
    id: 'CLI-105',
    name: 'Alexandre Abreu',
    company: 'Inova Contábil',
    email: 'alexandre@inovacontabil.com',
    phone: '(31) 94321-0987',
    active: true,
  },
];

export const INITIAL_TECHNICIANS: Technician[] = [
  {
    id: 'TEC-001',
    name: 'Carlos Eduardo',
    email: 'carlos.eduardo@techmanager.com',
    phone: '(11) 91234-5678',
    specialty: 'Redes',
    status: 'Ativo',
    ticketsCount: 4,
  },
  {
    id: 'TEC-002',
    name: 'Ana Paula Santos',
    email: 'ana.santos@techmanager.com',
    phone: '(11) 92345-6789',
    specialty: 'Software',
    status: 'Ocupado',
    ticketsCount: 2,
  },
  {
    id: 'TEC-003',
    name: 'Marcos Souza',
    email: 'marcos.souza@techmanager.com',
    phone: '(21) 93456-7890',
    specialty: 'Hardware',
    status: 'Ativo',
    ticketsCount: 3,
  },
  {
    id: 'TEC-004',
    name: 'Beatriz Melo',
    email: 'beatriz.melo@techmanager.com',
    phone: '(31) 94567-8901',
    specialty: 'Infraestrutura',
    status: 'Ativo',
    ticketsCount: 1,
  },
  {
    id: 'TEC-005',
    name: 'Bruno Dias',
    email: 'bruno.dias@techmanager.com',
    phone: '(11) 95678-9012',
    specialty: 'Redes',
    status: 'Inativo',
    ticketsCount: 0,
  },
];

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: 'CHA-1001',
    title: 'Falha de conexão no switch principal',
    priority: 'Crítica',
    category: 'Redes',
    location: 'Servidores / 3º Andar',
    equipment: 'Switch Cisco Catalyst 9300',
    description: 'Switch de distribuição principal não está respondendo ao ping interno. Todo o andar administrativo está sem rede cabeada e Wi-Fi fora do ar.',
    clientId: 'CLI-101',
    clientName: 'Roberto Alencar (Logística Alfa S.A.)',
    assignedTechnicianId: 'TEC-001',
    baseValue: 1250.00,
    finalValue: 1480.00,
    status: 'Em Andamento',
    creationDate: '23/05/2026, 08:30',
    slaEstimate: '4h',
    files: ['diagrama_rede.pdf', 'foto_leds_vermelhos.jpg'],
    updates: [
      {
        id: 'UPD-001',
        date: '23/05/2026, 08:35',
        author: 'Sistema',
        message: 'Chamado aberto automaticamente pelo monitoramento de rede.',
        statusChange: 'Pendente',
      },
      {
        id: 'UPD-002',
        date: '23/05/2026, 08:45',
        author: 'João Silva (Suporte)',
        message: 'Triagem efetuada. Técnico de prontidão atribuído devido à criticidade do sinistro.',
        statusChange: 'Em Andamento',
      },
      {
        id: 'UPD-003',
        date: '23/05/2026, 09:12',
        author: 'Carlos Eduardo',
        message: 'Chegada ao local. Verificado que a fonte principal parou de alimentar o barramento. Efetuando a troca pela fonte sobressalente no rack reserva.',
      }
    ],
  },
  {
    id: 'CHA-1002',
    title: 'Recuperação de dados RAID corrompido',
    priority: 'Alta',
    category: 'Hardware',
    location: 'TI / Térreo',
    equipment: 'Storage NAS Synology 8-Bay',
    description: 'O arranjo RAID 5 aponta 2 discos offline. É necessário substituição imediata e inicialização do rebuild usando dados de backup se houver integridade comprometida.',
    clientId: 'CLI-104',
    clientName: 'Juliana Mendes (Finanças Premium S.A.)',
    assignedTechnicianId: 'TEC-003',
    baseValue: 2450.00,
    finalValue: 2450.00,
    status: 'Em Andamento',
    creationDate: '22/05/2026, 14:15',
    slaEstimate: '24h',
    files: ['raid_status.png'],
    updates: [
      {
        id: 'UPD-004',
        date: '22/05/2026, 14:15',
        author: 'Juliana Mendes',
        message: 'Chamado de emergência aberto pelo financeiro. Dados de auditoria em risco.',
      },
      {
        id: 'UPD-005',
        date: '22/05/2026, 14:40',
        author: 'Marcos Souza',
        message: 'Técnico em trânsito com discos compatíveis para diagnóstico imediato e hot-spare.',
        statusChange: 'Em Andamento',
      }
    ],
  },
  {
    id: 'CHA-1003',
    title: 'Erro de licença no ERP Corporativo',
    priority: 'Média',
    category: 'Software',
    location: 'Faturamento / Sala 12',
    equipment: 'Terminal de Faturamento 04',
    description: 'O faturamento dos pedidos falha exibindo erro "Invalid License Signature" após última atualização do sistema comercial.',
    clientId: 'CLI-102',
    clientName: 'Carla Dias (Clínica Sorriso do Vale)',
    assignedTechnicianId: 'TEC-002',
    baseValue: 350.00,
    finalValue: 350.00,
    status: 'Pendente',
    creationDate: '23/05/2026, 10:10',
    slaEstimate: '8h',
    files: [],
    updates: [
      {
        id: 'UPD-006',
        date: '23/05/2026, 10:10',
        author: 'Carla Dias',
        message: 'Chamado aberto. O faturamento está parado.',
      }
    ],
  },
  {
    id: 'CHA-1004',
    title: 'Estruturação de cabeamento estruturado CAT6',
    priority: 'Baixa',
    category: 'Infraestrutura',
    location: 'Novo Bloco Comercial / Ala Leste',
    equipment: 'Rack de Distribuição 44U e Cabos Nexans',
    description: 'Instalação de 16 novos pontos de rede de dados e telefonia para a expansão do escritório administrativo.',
    clientId: 'CLI-103',
    clientName: 'Marcos Ponci (Supermercados Sul)',
    assignedTechnicianId: 'TEC-004',
    baseValue: 4800.00,
    finalValue: 5200.00,
    status: 'Resolvido',
    creationDate: '15/05/2026, 09:00',
    slaEstimate: '7 dias',
    files: ['projeto-ala-leste.dwg', 'fotos-obra.zip'],
    updates: [
      {
        id: 'UPD-007',
        date: '15/05/2026, 09:00',
        author: 'Marcos Ponci',
        message: 'Chamado agendado criado baseado no escopo aprovado anteriormente.',
      },
      {
        id: 'UPD-008',
        date: '15/05/2026, 13:30',
        author: 'Beatriz Melo',
        message: 'Iniciando passagem de guias e identificação dos dutos.',
        statusChange: 'Em Andamento',
      },
      {
        id: 'UPD-009',
        date: '18/05/2026, 17:00',
        author: 'Beatriz Melo',
        message: 'Cabeação finalizada, conexões crimpadas nos patch-panels e tomadas de parede. Certificação de cabos realizada com sucesso.',
        statusChange: 'Resolvido',
      }
    ],
  },
  {
    id: 'CHA-1005',
    title: 'Instalação de Câmeras de Monitoramento IP',
    priority: 'Média',
    category: 'Hardware',
    location: 'Estacionamento e Recepção',
    equipment: 'Câmeras Intelbras Dome IP Poe',
    description: 'Instalação de 4 câmeras IP adicionais e ampliação da capacidade de gravação do NVD para 30 dias de histórico.',
    clientId: 'CLI-103',
    clientName: 'Marcos Ponci (Supermercados Sul)',
    assignedTechnicianId: 'TEC-003',
    baseValue: 1800.00,
    finalValue: 2100.00,
    status: 'Resolvido',
    creationDate: '10/05/2026, 11:15',
    slaEstimate: '3 dias',
    files: [],
    updates: [
      {
        id: 'UPD-010',
        date: '12/05/2026, 16:00',
        author: 'Marcos Souza',
        message: 'Serviço concluído, câmeras configuradas no monitor central e aplicativo móvel.',
        statusChange: 'Resolvido',
      }
    ],
  },
];

export const INITIAL_BACKUPS: BackupHistory[] = [
  { id: 'BCK-001', type: 'Geral', size: '142.5 GB', status: 'Sucesso', date: '21/05/2026, 23:00' },
  { id: 'BCK-002', type: 'Incremental', size: '14.2 GB', status: 'Sucesso', date: '22/05/2026, 23:00' },
  { id: 'BCK-003', type: 'Incremental', size: '15.8 GB', status: 'Sucesso', date: '23/05/2026, 23:00' },
  { id: 'BCK-004', type: 'Incremental', size: '2.1 GB', status: 'Falha', date: '20/05/2026, 11:30' },
  { id: 'BCK-005', type: 'Geral', size: '139.8 GB', status: 'Sucesso', date: '14/05/2026, 23:00' },
];

export const INITIAL_BACKUP_CONFIG: BackupConfig = {
  frequency: 'Diário',
  startDate: '2026-05-24',
  startHour: '23:00',
  cloudSync: true,
  integrityCheck: true,
};
